CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    dep_name VARCHAR(100) NOT NULL,
    is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE employees (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    position VARCHAR(100) NOT NULL,
    department_id BIGINT NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    FOREIGN KEY (department_id) REFERENCES departments(id)
);

CREATE TABLE overtimes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employees_id BIGINT NOT NULL,
    work_date DATE NOT NULL,
    reason VARCHAR(50) NOT NULL,
    hours INTEGER NOT NULL,
    FOREIGN KEY (employees_id) REFERENCES employees(id)
);

CREATE TABLE day_offs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employees_id BIGINT NOT NULL,
    date DATE NOT NULL,
    FOREIGN KEY (employees_id) REFERENCES employees(id)
);
